networks:
  default:
    external:
      name: roboshop
volumes:
  mongodb: #docker volume create mongodb
  redis:
  mysql:
  rabbitmq:
services:
  # docker run -d --name mongodb --network=roboshop mongodb:1
  mongodb:
    build: ./mongodb
    container_name: mongodb
    volumes:
    - source: mongodb
      target: /data/db
      type: volume
    # networks:
    # - roboshop

  catalogue:
    build: ./catalogue
    container_name: catalogue
    # networks:
    # - roboshop
    depends_on:
    - mongodb

  web:
    build: ./web
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    - shipping
    - payment

  redis:
    image: redis
    container_name: redis
    volumes:
    - source: redis
      target: /data
      type: volume

  user:
    build: ./user
    container_name: user
    depends_on:
    - redis
    - mongodb

  cart:
    build: ./cart
    container_name: cart
    depends_on:
    - redis
    - catalogue

  mysql:
    build: ./mysql
    container_name: mysql
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume

  shipping:
    build: ./shipping
    container_name: shipping
    depends_on:
    - mysql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER=roboshop
    - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
    - source: rabbitmq
      target: /var/lib/rabbitmq
      type: volume

  payment:
    container_name: payment
    build: ./payment
    depends_on:
    - rabbitmq
    - user
    - cart

