pipeline {
    agent any

    environment {
        HUB_REPO = 'MongoDb'
        IMAGE_TAG = "%{BUILD_NUMBER}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/GOTTAMREDDY/Applications.git'
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'Docker_details',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    bat '''
                    echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
                    '''
                }
            }
        }

        stage('Build & Pubat Image') {
            steps {
                bat '''
                ls -l
                cd /Applications/MongoDB
                docker build -t MongoDb:%{BUILD_NUMBER}% .
                docker tag MongoDb:%{BUILD_NUMBER}% sadashivareddy/MongoDb:%{BUILD_NUMBER}%
                docker push sadashivareddy/MongoDb:%{BUILD_NUMBER}%
                '''
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }
        failure {
            echo 'Pipeline Failed!'
        }
    }
}