pipeline {
    agent any

    environment {
        HUB_REPO = 'mongodb'
        IMAGE_TAG = "${BUILD_NUMBER}"
        DOCKER_USER = "sadashivareddy"
        RELEASE_NAME = "mongodb-release"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/GOTTAMREDDY/Applications.git'
            }
        }

        stage('Docker Login') {
            steps {
                bat '''
                docker login -u sadashivareddy  -p MyDocker@123
                '''
            }
        }

        stage('Build & Push Image') {
            steps {
                bat '''
                cd MongoDB

                docker build -t mongodb:%BUILD_NUMBER% .
                docker tag mongodb:%BUILD_NUMBER% sadashivareddy/mongodb:%BUILD_NUMBER%
                docker push sadashivareddy/mongodb:%BUILD_NUMBER%
                '''
            }
        }

        stage('Deploy using Helm') {
            steps {
                bat '''
                cd MongoDB\\mongodb-chart

                helm upgrade --install mongodb-release . ^
                --set image.repository=sadashivareddy/mongodb ^
                --set image.tag=%BUILD_NUMBER%
                '''
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }
        failure {
            echo 'Pipeline Failed!'
        }
    }
}