pipeline {
    agent any

    environment {
        HUB_REPO = 'MongoDb'
        IMAGE_TAG = '%{BUILD_NUMBER}'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/GOTTAMREDDY/Applications.git'
            }
        }

        stage('Docker Login') {
            steps {
                    bat '''
                    docker login -u sadashivareddy -p MyDocker@123
                    '''
            }
        }

        stage('Build & Pubat Image') {
            steps {
                bat '''
                docker build -t MongoDb:%{IMAGE_TAG}% .
                docker tag MongoDb:%{IMAGE_TAG}% sadashivareddy/MongoDb:%{IMAGE_TAG}%
                docker push sadashivareddy/MongoDb:%{IMAGE_TAG}%
                '''
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }
        failure {
            echo 'Pipeline Failed!'
        }
    }
}
