FROM nginx:alpine
RUN rm -rf /etc/nginx/nginx.conf
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY roboshop.conf /etc/nginx/nginx.conf
ADD static /usr/share/nginx/html/
EXPOSE 80
CMD [ "nginx","-g","daemon off;" ]